# /cfgman/rb/load-internal - config/_internal/settings.xml
GET http://localhost:9090/api/cfgman/rb/load-internal?path=/config/_internal/settings.xml             
Content-Type: application/json             

###

# /cfgman/rb/load - config/_defaults/settings.xml
GET http://localhost:9090/cfgman/rb/load?path=C:/Projects/all-repos/src/products/reportburster-server-java/frontend/reporting/testground/e2e/config/_defaults/settings.xml             
Content-Type: application/json             

###

# /jobman/system/check-url
GET http://localhost:9090/jobman/system/check-url?url=http://localhost:8025        
Content-Type: application/json

###

# /jobman/system/unix-cli - cat eml-contact.xml
GET http://localhost:9090/jobman/system/unix-cli/cat?filePath=C:/Projects/all-repos/src/products/reportburster-server-java/frontend/reporting/testground/e2e/config/connections/eml-contact.xml             
Content-Type: application/json

###

# /jobman/system/unix-cli - find config/connections/*.xml
GET http://localhost:9090/jobman/system/unix-cli/find?path=C:/Projects/all-repos/src/products/reportburster-server-java/frontend/reporting/testground/e2e/config/connections&matching=*.xml             
Content-Type: application/json

###

# /jobman/system/unix-cli - find config/burst/*.xml
GET http://localhost:9090/jobman/system/unix-cli/find?path=C:/Projects/all-repos/src/products/reportburster-server-java/frontend/reporting/testground/e2e/config/burst&matching=*.xml&files=true&directories=false             
Content-Type: application/json

###

# /jobman/system/fs/exists
GET http://localhost:9090/jobman/system/fs/exists?paths=C:/Projects/all-repos/src/products/reportburster-server-java/frontend/reporting/testground/e2e/temp             
Content-Type: application/json


###

# /jobman/system/fs/read-file-to-string
GET http://localhost:9090/jobman/system/fs/read-file-to-string?filePath=C:/Projects/all-repos/src/products/reportburster-server-java/frontend/reporting/testground/e2e/config/_internal/license.xml            
Content-Type: application/json

###

# /jobman/system/fs/resolve
GET http://localhost:9090/jobman/system/fs/resolve?paths=config/burst/settings.xml             
Content-Type: application/json

###

# /jobman/logs/tailer
### Put request to start log tailer
PUT http://localhost:9090/jobman/logs/tailer
content-type: application/json

{
    "fileName": "errors.log",
    "command": "start"
}

### 
# @name uploadMultipleFiles
POST http://localhost:9090/jobman/upload/process-multiple
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="file1.txt"
Content-Type: text/plain

< C:/PATH_backups_ChocolateyUninstall.txt
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="file2.txt"
Content-Type: text/plain

< C:/PATH_backups_ChocolateyUninstall.txt
--WebAppBoundary--