specs:
  dir: specs

jobs:
  dir: jobs

workingDirs:
  dir: wds

  removeAfterExecution:
    enabled: false

users:
  file: users

authentication:
  type: guest  # guest/basic/custom

execution:
  maxConcurrentJobs: 10
  delayBeforeForciblyKillingJobs: PT3S  # ISO 8601 duration

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      logFormat: "%d{yy/MM/dd HH:mm:ss} %-5p %c: %m%n"