version: "3.8"
services:
  vanna-ai:
    container_name: vanna-ai
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8095:8501" # Streamlit runs on 8501 by default
    volumes:
      - vanna-data:/opt/data
      - ./config:/opt/config
    environment:
      - API_KEY=${API_KEY:-demo}
      - CUSTOM_LLM_BASE_URL=${CUSTOM_LLM_BASE_URL}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME:-gpt-4}
      - VANNA_DEFAULT_DB_TYPE=sqlite
      - VANNA_DEFAULT_DB_PATH=/opt/data/default.sqlite3
    networks:
      - rb-network

volumes:
  vanna-data:

networks:
  rb-network:
    external: false
