version: "3.8"

services:
  reportburster-server:
    image: reportburster-server:10.1.1
    ports:
      - "9090:9090"
    # environment:
    # - POLLING_PATH=/app/poll
    volumes:
      - ./config:/app/config
      - ./input-files:/app/input-files
      - ./logs:/app/logs
      - ./output:/app/output
      - ./quarantine:/app/quarantine
      - ./poll:/app/poll
      - ./samples:/app/samples
      - ./scripts:/app/scripts

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - "8025:8025"
