'use client';

import { useState, use, useEffect, useRef } from 'react';
import Link from 'next/link';
import { ChevronLeft, ChevronRight, FileText, Folder, FolderOpen, File } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { CodeEditor } from '@/components/CodeEditor';
import { PreviewPanel } from '@/components/PreviewPanel';

// Sample agent workspace structure - will be replaced with real Letta workspace
const sampleWorkspace = {
  'agent-1': {
    name: 'Research Assistant',
    files: [
      {
        path: 'README.md',
        type: 'markdown',
        content: `# Research Assistant Agent

This agent specializes in research tasks, data analysis, and information summarization.

## Capabilities
- Data analysis and pattern recognition
- Information gathering and synthesis
- Report generation
- Citation management

## Usage
Simply ask the agent to research a topic or analyze data.`,
      },
      {
        path: 'config.json',
        type: 'json',
        content: `{
  "name": "Research Assistant",
  "version": "1.0.0",
  "model": "gpt-4",
  "tools": [
    "web_search",
    "data_analysis",
    "summarization"
  ],
  "temperature": 0.7,
  "max_tokens": 2048
}`,
      },
      {
        path: 'prompts/system.txt',
        type: 'text',
        content: `You are a research assistant specialized in gathering, analyzing, and synthesizing information.

Your primary responsibilities:
1. Conduct thorough research on requested topics
2. Analyze data and identify patterns
3. Provide well-structured summaries
4. Cite sources accurately

Always maintain objectivity and cite your sources.`,
      },
      {
        path: 'docs/architecture.uml',
        type: 'uml',
        content: `@startuml
actor User
participant "Research Agent" as Agent
database "Knowledge Base" as KB
participant "Web Search" as Search

User -> Agent: Request research
Agent -> Search: Query topic
Search --> Agent: Results
Agent -> KB: Store findings
Agent -> Agent: Analyze & synthesize
Agent --> User: Research report
@enduml`,
      },
      {
        path: 'workflow.org',
        type: 'org',
        content: `* Research Workflow
** TODO Research Phase
   - [ ] Gather initial sources
   - [ ] Identify key themes
   - [ ] Validate information
** IN PROGRESS Analysis Phase
   - [X] Data collection
   - [ ] Pattern identification
   - [ ] Synthesis
** DONE Reporting Phase
   - [X] Draft report
   - [X] Cite sources`,
      },
      {
        path: 'examples/sample-report.html',
        type: 'html',
        content: `<!DOCTYPE html>
<html>
<head>
  <title>Sample Research Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; }
    h1 { color: #22a7c8; }
    .citation { color: #666; font-size: 0.9em; }
  </style>
</head>
<body>
  <h1>Research Findings: AI Agent Architecture</h1>
  <p>This report summarizes key findings on AI agent architecture patterns.</p>
  <h2>Key Findings</h2>
  <ul>
    <li>Modular design improves maintainability</li>
    <li>Tool integration enhances capabilities</li>
    <li>Context management is critical</li>
  </ul>
  <p class="citation">Generated by Research Assistant Agent</p>
</body>
</html>`,
      },
      {
        path: 'scripts/AgentService.groovy',
        type: 'groovy',
        content: `package com.letta.agent

import groovy.transform.CompileStatic

/**
 * Agent Service - Manages AI agent lifecycle
 */
@CompileStatic
class AgentService {

    String agentId
    String name
    Map<String, Object> config

    AgentService(String name, Map config) {
        this.name = name
        this.config = config
        this.agentId = UUID.randomUUID().toString()
    }

    def initialize() {
        println "Initializing agent: \${name}"
        loadTools()
        loadMemory()
    }

    private void loadTools() {
        config.tools?.each { tool ->
            println "Loading tool: \${tool}"
        }
    }

    private void loadMemory() {
        println "Loading memory for agent \${agentId}"
    }

    String processMessage(String message) {
        return "Agent \${name} received: \${message}"
    }
}`,
      },
    ],
  },
  // Add more agents...
};

type FileNode = {
  path: string;
  type: string;
  content: string;
};

export default function AgentDetailsPage({ params }: { params: Promise<{ agentId: string }> }) {
  const { agentId } = use(params);
  const [selectedFile, setSelectedFile] = useState<FileNode | null>(null);
  const [leftPanelWidth, setLeftPanelWidth] = useState(20); // percentage
  const [rightPanelWidth, setRightPanelWidth] = useState(30); // percentage
  const [isResizingLeft, setIsResizingLeft] = useState(false);
  const [isResizingRight, setIsResizingRight] = useState(false);
  const [expandedFolders, setExpandedFolders] = useState<Set<string>>(new Set(['prompts', 'docs', 'examples']));
  const [mobilePanel, setMobilePanel] = useState<'files' | 'editor' | 'preview'>('editor');
  const [isLeftPanelCollapsed, setIsLeftPanelCollapsed] = useState(false);
  const [isEditorPanelCollapsed, setIsEditorPanelCollapsed] = useState(false);

  // Get agent workspace
  const workspace = (sampleWorkspace as any)[agentId];

  if (!workspace) {
    return (
      <div className="w-full py-8 px-4">
        <div className="max-w-7xl mx-auto">
          <Link href="/agents" className="text-rb-cyan hover:underline mb-4 inline-block">
            ← Back to Agents
          </Link>
          <p className="text-muted-foreground">Agent not found</p>
        </div>
      </div>
    );
  }

  // Build file tree structure
  const fileTree: { [key: string]: FileNode[] } = {};
  workspace.files.forEach((file: FileNode) => {
    const parts = file.path.split('/');
    if (parts.length === 1) {
      // Root file
      if (!fileTree['_root']) fileTree['_root'] = [];
      fileTree['_root'].push(file);
    } else {
      // File in folder
      const folder = parts[0];
      if (!fileTree[folder]) fileTree[folder] = [];
      fileTree[folder].push(file);
    }
  });

  const toggleFolder = (folder: string) => {
    const newExpanded = new Set(expandedFolders);
    if (newExpanded.has(folder)) {
      newExpanded.delete(folder);
    } else {
      newExpanded.add(folder);
    }
    setExpandedFolders(newExpanded);
  };

  const getLanguage = (type: string): string => {
    const map: { [key: string]: string } = {
      markdown: 'markdown',
      json: 'json',
      text: 'plaintext',
      html: 'markup', // Prism uses 'markup' for HTML
      uml: 'plantuml', // Custom PlantUML language definition
      org: 'orgmode', // Custom Org-mode language definition
      groovy: 'groovy', // Native Prism Groovy support
      js: 'javascript',
      ts: 'typescript',
      py: 'python',
    };
    return map[type] || 'plaintext';
  };

  const renderPreview = () => {
    if (!selectedFile) {
      return (
        <div className="flex items-center justify-center h-full text-muted-foreground">
          Select a file to preview
        </div>
      );
    }

    // Extract filename from path (last segment after /)
    const fileName = selectedFile.path.split('/').pop() || selectedFile.path;

    return (
      <PreviewPanel
        fileName={fileName}
        fileContent={selectedFile.content}
        language={getLanguage(selectedFile.type)}
      />
    );
  };

  return (
    <div className="w-full h-screen flex flex-col">
      {/* Header */}
      <div className="border-b border-border px-4 py-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Link href="/agents" className="text-rb-cyan hover:underline">
              ← Back
            </Link>
            <h1 className="text-xl font-bold">{workspace.name}</h1>
          </div>

          {/* Mobile Panel Selector */}
          <div className="flex md:hidden gap-1">
            <Button
              variant={mobilePanel === 'files' ? 'default' : 'outline'}
              size="sm"
              onClick={() => setMobilePanel('files')}
            >
              Files
            </Button>
            <Button
              variant={mobilePanel === 'editor' ? 'default' : 'outline'}
              size="sm"
              onClick={() => setMobilePanel('editor')}
            >
              Code
            </Button>
            <Button
              variant={mobilePanel === 'preview' ? 'default' : 'outline'}
              size="sm"
              onClick={() => setMobilePanel('preview')}
            >
              Preview
            </Button>
          </div>
        </div>
      </div>

      {/* Three-panel layout */}
      <div className="flex-1 flex overflow-hidden">
        {/* LEFT PANEL: File Explorer */}
        <div
          className={`border-r border-border bg-card overflow-y-auto transition-all duration-300 ${
            mobilePanel === 'files' ? 'block' : 'hidden'
          } md:block ${isLeftPanelCollapsed ? 'md:!w-12' : ''}`}
          style={isLeftPanelCollapsed ? undefined : { width: `${leftPanelWidth}%`, minWidth: '200px' }}
        >
          {isLeftPanelCollapsed ? (
            <div className="flex flex-col items-center py-4">
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setIsLeftPanelCollapsed(false)}
                className="hover:bg-muted"
                title="Expand file explorer"
              >
                <ChevronRight className="w-4 h-4" />
              </Button>
              <div className="mt-4 text-xs text-muted-foreground rotate-90 whitespace-nowrap origin-center">
                FILES
              </div>
            </div>
          ) : (
            <div className="relative h-full">
              <div className="absolute top-2 right-2 z-10">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => setIsLeftPanelCollapsed(true)}
                  className="hover:bg-muted"
                  title="Collapse file explorer"
                >
                  <ChevronLeft className="w-4 h-4" />
                </Button>
              </div>
              <div className="p-4">
                <h3 className="font-semibold mb-3 text-sm text-muted-foreground">WORKSPACE</h3>

            {/* Root files */}
            {fileTree['_root']?.map((file) => (
              <button
                key={file.path}
                onClick={() => setSelectedFile(file)}
                className={`w-full flex items-center gap-2 px-2 py-1.5 rounded text-sm hover:bg-muted transition-colors ${
                  selectedFile?.path === file.path ? 'bg-rb-cyan/10 text-rb-cyan' : 'text-foreground'
                }`}
              >
                <FileText className="w-4 h-4 flex-shrink-0" />
                <span className="truncate">{file.path}</span>
              </button>
            ))}

            {/* Folders */}
            {Object.keys(fileTree).filter(k => k !== '_root').sort().map((folder) => (
              <div key={folder} className="mt-2">
                <button
                  onClick={() => toggleFolder(folder)}
                  className="w-full flex items-center gap-2 px-2 py-1.5 rounded text-sm hover:bg-muted transition-colors text-foreground"
                >
                  {expandedFolders.has(folder) ? (
                    <FolderOpen className="w-4 h-4 flex-shrink-0 text-rb-cyan" />
                  ) : (
                    <Folder className="w-4 h-4 flex-shrink-0 text-rb-cyan" />
                  )}
                  <span className="truncate font-medium">{folder}</span>
                  <ChevronRight
                    className={`w-4 h-4 ml-auto transition-transform ${
                      expandedFolders.has(folder) ? 'rotate-90' : ''
                    }`}
                  />
                </button>

                {expandedFolders.has(folder) && (
                  <div className="ml-4 mt-1">
                    {fileTree[folder].map((file) => {
                      const fileName = file.path.split('/').pop();
                      return (
                        <button
                          key={file.path}
                          onClick={() => setSelectedFile(file)}
                          className={`w-full flex items-center gap-2 px-2 py-1.5 rounded text-sm hover:bg-muted transition-colors ${
                            selectedFile?.path === file.path ? 'bg-rb-cyan/10 text-rb-cyan' : 'text-foreground'
                          }`}
                        >
                          <File className="w-4 h-4 flex-shrink-0" />
                          <span className="truncate">{fileName}</span>
                        </button>
                      );
                    })}
                  </div>
                )}
              </div>
            ))}
              </div>
            </div>
          )}
        </div>

        {/* Resize handle for left panel */}
        <div
          className="hidden md:block w-1 bg-border hover:bg-rb-cyan cursor-col-resize transition-colors"
          onMouseDown={() => setIsResizingLeft(true)}
        />

        {/* CENTER PANEL: Code Editor */}
        <div
          className={`flex-1 overflow-hidden transition-all duration-300 ${
            mobilePanel === 'editor' ? 'block' : 'hidden'
          } md:block ${isEditorPanelCollapsed ? 'md:!w-12' : ''}`}
          style={isEditorPanelCollapsed ? undefined : { width: `${100 - leftPanelWidth - rightPanelWidth}%` }}
        >
          {isEditorPanelCollapsed ? (
            <div className="flex flex-col items-center py-4 bg-card border-r border-border h-full">
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setIsEditorPanelCollapsed(false)}
                className="hover:bg-muted"
                title="Expand code editor"
              >
                <ChevronRight className="w-4 h-4" />
              </Button>
              <div className="mt-4 text-xs text-muted-foreground rotate-90 whitespace-nowrap origin-center">
                CODE
              </div>
            </div>
          ) : selectedFile ? (
            <div className="h-full flex flex-col relative">
              <div className="border-b border-border px-4 py-2 bg-muted/30 flex items-center justify-between">
                <p className="text-sm font-medium text-foreground">{selectedFile.path}</p>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => setIsEditorPanelCollapsed(true)}
                  className="hover:bg-muted"
                  title="Collapse code editor"
                >
                  <ChevronLeft className="w-4 h-4" />
                </Button>
              </div>
              <div className="flex-1 overflow-auto">
                <CodeEditor
                  code={selectedFile.content}
                  language={getLanguage(selectedFile.type)}
                  fileName={selectedFile.path}
                />
              </div>
            </div>
          ) : (
            <div className="h-full flex items-center justify-center text-muted-foreground">
              Select a file to view its contents
            </div>
          )}
        </div>

        {/* Resize handle for right panel */}
        <div
          className="hidden md:block w-1 bg-border hover:bg-rb-cyan cursor-col-resize transition-colors"
          onMouseDown={() => setIsResizingRight(true)}
        />

        {/* RIGHT PANEL: Smart Preview */}
        <div
          className={`border-l border-border bg-card overflow-y-auto ${
            mobilePanel === 'preview' ? 'block' : 'hidden'
          } md:block`}
          style={{ width: `${rightPanelWidth}%`, minWidth: '250px' }}
        >
          {renderPreview()}
        </div>
      </div>
    </div>
  );
}
