// Country name → ISO-3166-1 alpha-2 code (lowercase).
// Covers the common aliases real-world data uses: "USA" / "United States" /
// "U.S." / "US" all map to "us"; "UK" / "United Kingdom" / "Great Britain" all
// map to "gb". Follows the same mapping approach as established BI references so choropleth
// joins work on the same inputs.
//
// Normalization: the lookup is keyed by lowercase + stripped of non-letters.
// `normalizeCountryName("U.K.")` → "uk" → "gb".

const CODES_BY_NAME: Record<string, string> = {
  // A
  afghanistan: "af", af: "af",
  albania: "al", al: "al",
  algeria: "dz", dz: "dz",
  andorra: "ad", ad: "ad",
  angola: "ao", ao: "ao",
  "antiguaandbarbuda": "ag", ag: "ag",
  argentina: "ar", ar: "ar",
  armenia: "am", am: "am",
  australia: "au", au: "au",
  austria: "at", at: "at",
  azerbaijan: "az", az: "az",
  // B
  bahamas: "bs", bs: "bs",
  bahrain: "bh", bh: "bh",
  bangladesh: "bd", bd: "bd",
  barbados: "bb", bb: "bb",
  belarus: "by", by: "by",
  belgium: "be", be: "be",
  belize: "bz", bz: "bz",
  benin: "bj", bj: "bj",
  bhutan: "bt", bt: "bt",
  bolivia: "bo", bo: "bo",
  bosnia: "ba", "bosniaandherzegovina": "ba", ba: "ba",
  botswana: "bw", bw: "bw",
  brazil: "br", br: "br",
  brunei: "bn", bn: "bn",
  bulgaria: "bg", bg: "bg",
  "burkinafaso": "bf", bf: "bf",
  burundi: "bi", bi: "bi",
  // C
  cambodia: "kh", kh: "kh",
  cameroon: "cm", cm: "cm",
  canada: "ca", ca: "ca",
  "capeverde": "cv", "caboverde": "cv", cv: "cv",
  "centralafricanrepublic": "cf", cf: "cf",
  chad: "td", td: "td",
  chile: "cl", cl: "cl",
  china: "cn", "prchina": "cn", "peoplesrepublicofchina": "cn", cn: "cn",
  colombia: "co", co: "co",
  comoros: "km", km: "km",
  "congo": "cg", "republicofthecongo": "cg", cg: "cg",
  "democraticrepublicofthecongo": "cd", "drcongo": "cd", "dcongo": "cd", cd: "cd",
  "costarica": "cr", cr: "cr",
  "cotedivoire": "ci", "ivorycoast": "ci", ci: "ci",
  croatia: "hr", hr: "hr",
  cuba: "cu", cu: "cu",
  cyprus: "cy", cy: "cy",
  "czechrepublic": "cz", czechia: "cz", cz: "cz",
  // D
  denmark: "dk", dk: "dk",
  djibouti: "dj", dj: "dj",
  dominica: "dm", dm: "dm",
  "dominicanrepublic": "do", do: "do",
  // E
  ecuador: "ec", ec: "ec",
  egypt: "eg", eg: "eg",
  "elsalvador": "sv", sv: "sv",
  "equatorialguinea": "gq", gq: "gq",
  eritrea: "er", er: "er",
  estonia: "ee", ee: "ee",
  eswatini: "sz", swaziland: "sz", sz: "sz",
  ethiopia: "et", et: "et",
  // F
  fiji: "fj", fj: "fj",
  finland: "fi", fi: "fi",
  france: "fr", fr: "fr",
  // G
  gabon: "ga", ga: "ga",
  gambia: "gm", gm: "gm",
  georgia: "ge", ge: "ge",
  germany: "de", de: "de", deutschland: "de",
  ghana: "gh", gh: "gh",
  greece: "gr", gr: "gr",
  grenada: "gd", gd: "gd",
  guatemala: "gt", gt: "gt",
  guinea: "gn", gn: "gn",
  "guineabissau": "gw", gw: "gw",
  guyana: "gy", gy: "gy",
  // H
  haiti: "ht", ht: "ht",
  honduras: "hn", hn: "hn",
  "hongkong": "hk", hk: "hk",
  hungary: "hu", hu: "hu",
  // I
  iceland: "is", is: "is",
  india: "in", in: "in",
  indonesia: "id", id: "id",
  iran: "ir", ir: "ir",
  iraq: "iq", iq: "iq",
  ireland: "ie", "republicofireland": "ie", ie: "ie",
  israel: "il", il: "il",
  italy: "it", it: "it",
  // J
  jamaica: "jm", jm: "jm",
  japan: "jp", jp: "jp",
  jordan: "jo", jo: "jo",
  // K
  kazakhstan: "kz", kz: "kz",
  kenya: "ke", ke: "ke",
  kiribati: "ki", ki: "ki",
  kosovo: "xk", xk: "xk",
  kuwait: "kw", kw: "kw",
  kyrgyzstan: "kg", kg: "kg",
  // L
  laos: "la", la: "la",
  latvia: "lv", lv: "lv",
  lebanon: "lb", lb: "lb",
  lesotho: "ls", ls: "ls",
  liberia: "lr", lr: "lr",
  libya: "ly", ly: "ly",
  liechtenstein: "li", li: "li",
  lithuania: "lt", lt: "lt",
  luxembourg: "lu", lu: "lu",
  // M
  macau: "mo", macao: "mo", mo: "mo",
  madagascar: "mg", mg: "mg",
  malawi: "mw", mw: "mw",
  malaysia: "my", my: "my",
  maldives: "mv", mv: "mv",
  mali: "ml", ml: "ml",
  malta: "mt", mt: "mt",
  "marshallislands": "mh", mh: "mh",
  mauritania: "mr", mr: "mr",
  mauritius: "mu", mu: "mu",
  mexico: "mx", mx: "mx",
  micronesia: "fm", fm: "fm",
  moldova: "md", md: "md",
  monaco: "mc", mc: "mc",
  mongolia: "mn", mn: "mn",
  montenegro: "me", me: "me",
  morocco: "ma", ma: "ma",
  mozambique: "mz", mz: "mz",
  myanmar: "mm", burma: "mm", mm: "mm",
  // N
  namibia: "na", na: "na",
  nauru: "nr", nr: "nr",
  nepal: "np", np: "np",
  netherlands: "nl", holland: "nl", thenetherlands: "nl", nl: "nl",
  "newzealand": "nz", nz: "nz",
  nicaragua: "ni", ni: "ni",
  niger: "ne", ne: "ne",
  nigeria: "ng", ng: "ng",
  "northkorea": "kp", "dprk": "kp", kp: "kp",
  "northmacedonia": "mk", macedonia: "mk", mk: "mk",
  norway: "no", no: "no",
  // O
  oman: "om", om: "om",
  // P
  pakistan: "pk", pk: "pk",
  palau: "pw", pw: "pw",
  palestine: "ps", ps: "ps",
  panama: "pa", pa: "pa",
  "papuanewguinea": "pg", pg: "pg",
  paraguay: "py", py: "py",
  peru: "pe", pe: "pe",
  philippines: "ph", ph: "ph",
  poland: "pl", pl: "pl",
  portugal: "pt", pt: "pt",
  "puertorico": "pr", pr: "pr",
  // Q
  qatar: "qa", qa: "qa",
  // R
  romania: "ro", ro: "ro",
  russia: "ru", "russianfederation": "ru", ru: "ru",
  rwanda: "rw", rw: "rw",
  // S
  "saintkittsandnevis": "kn", kn: "kn",
  "saintlucia": "lc", lc: "lc",
  "saintvincentandthegrenadines": "vc", vc: "vc",
  samoa: "ws", ws: "ws",
  "sanmarino": "sm", sm: "sm",
  "saotomeandprincipe": "st", st: "st",
  "saudiarabia": "sa", sa: "sa",
  senegal: "sn", sn: "sn",
  serbia: "rs", rs: "rs",
  seychelles: "sc", sc: "sc",
  "sierraleone": "sl", sl: "sl",
  singapore: "sg", sg: "sg",
  slovakia: "sk", sk: "sk",
  slovenia: "si", si: "si",
  "solomonislands": "sb", sb: "sb",
  somalia: "so", so: "so",
  "southafrica": "za", za: "za",
  "southkorea": "kr", korea: "kr", "republicofkorea": "kr", kr: "kr",
  "southsudan": "ss", ss: "ss",
  spain: "es", es: "es",
  "srilanka": "lk", lk: "lk",
  sudan: "sd", sd: "sd",
  suriname: "sr", sr: "sr",
  sweden: "se", se: "se",
  switzerland: "ch", ch: "ch",
  syria: "sy", sy: "sy",
  // T
  taiwan: "tw", tw: "tw",
  tajikistan: "tj", tj: "tj",
  tanzania: "tz", tz: "tz",
  thailand: "th", th: "th",
  "timor-leste": "tl", "easttimor": "tl", tl: "tl",
  togo: "tg", tg: "tg",
  tonga: "to", to: "to",
  "trinidadandtobago": "tt", tt: "tt",
  tunisia: "tn", tn: "tn",
  turkey: "tr", "turkiye": "tr", tr: "tr",
  turkmenistan: "tm", tm: "tm",
  tuvalu: "tv", tv: "tv",
  // U
  uganda: "ug", ug: "ug",
  ukraine: "ua", ua: "ua",
  "unitedarabemirates": "ae", uae: "ae", ae: "ae",
  "unitedkingdom": "gb", uk: "gb", "greatbritain": "gb", britain: "gb",
    england: "gb", scotland: "gb", wales: "gb", "northernireland": "gb", gb: "gb",
  "unitedstates": "us", "unitedstatesofamerica": "us",
    usa: "us", us: "us", america: "us",
  uruguay: "uy", uy: "uy",
  uzbekistan: "uz", uz: "uz",
  // V
  vanuatu: "vu", vu: "vu",
  "vaticancity": "va", va: "va",
  venezuela: "ve", ve: "ve",
  vietnam: "vn", vn: "vn",
  // Y
  yemen: "ye", ye: "ye",
  // Z
  zambia: "zm", zm: "zm",
  zimbabwe: "zw", zw: "zw",
};

/** Normalize a raw country value (name or code) → ISO-3166 alpha-2 (lowercase)
 *  or null when unknown. Ignores punctuation, spaces and case. */
export function normalizeCountryToIso2(raw: unknown): string | null {
  if (raw == null) return null;
  const key = String(raw).toLowerCase().replace(/[^a-z]/g, "");
  if (!key) return null;
  return CODES_BY_NAME[key] ?? null;
}
