FROM wordpress:cli-2.12.0-php8.4

# Switch to root to be able to write to /usr/local/bin
USER root

# install Composer CLI
RUN set -e && \
    curl -sS https://getcomposer.org/installer | php -- --version=2.8.11 && \
    mv composer.phar /usr/local/bin/composer && \
    chmod +x /usr/local/bin/composer