FROM wordpress:cli-2.12.0-php8.4

# Switch to root to be able to write to /usr/local/bin
USER root

# install Composer CLI
RUN curl -sS https://getcomposer.org/installer | php \
 && mv composer.phar /usr/local/bin/composer