services:
  # Chainlit service for the main Vanna application
  reportburster-chat2db:
    build:
      context: src
      dockerfile: Dockerfile.vanna
    container_name: reportburster-chat2db
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
     - reportburster-chromadb
    
  # Jupyter Notebooks for training Vanna
  reportburster-notebooks:
    build:
      context: src
      dockerfile: Dockerfile.jupyter
    container_name: reportburster-notebooks
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
     - reportburster-chromadb
      
  # ChromaDB for vector storage
  reportburster-chromadb:
    image: chromadb/chroma:0.4.22
    container_name: reportburster-chromadb
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - vanna_chroma:/chroma/chroma
    
volumes:
  vanna_chroma:
    driver: local