== Overview

The scope of this document is to show how _DocumentBurster_(C) can be used to achieve more complex report delivery scenarios.

=== What to Expect

In this document, you'll learn how to

* Script _DocumentBurster_(C) to achieve complex use cases
* Get yourself familiar with the sample scripts provided with _DocumentBurster_(C)
* Upload reports using cURL

From time to time, some report distribution requirements might need to execute an external program during the report bursting lifecycle, distribute SMS messages, upload reports to enterprise portals, send reports by Fax or to print the output burst reports. In other situations it might be required to upload the reports using more secure protocols such as FTPs, SFTP or SCP. Before sending the reports, it is also possible to encrypt the output reports or stamp the distributed reports in much the same way that it is applied a rubber stamp to a paper document. 

=== _DocumentBurster_(C) scripting

If required, _DocumentBurster_(C) can be scripted in order to support advanced customized report distribution needs.

While it might look like an overkill to write scripts for doing report distribution, it is actually a powerful and flexible approach for implementing very specific requirements. Furthermore, the default _DocumentBurster_(C) software package is coming with a set of already written scripts which can be used almost out of the box.

In most of the real life situations, just taking an existing script (appropriate for the task in hand) and doing very small adjustments (for example giving FTP host, username and password) will be all that is required to achieve complex requirements. 

=== _cURL_ integration

_DocumentBurster_(C) does not reinvent the wheel and it integrates with *_cURL_* in order to achieve the most complex document distribution situations.

http://curl.haxx.se/[http://curl.haxx.se/,window=_blank]

_DocumentBurster_(C) does offer close integration with cURL, a command line tool for transferring data with URL syntax, supporting DICT, FILE, FTP, FTPS, GOPHER, HTTP, HTTPS, IMAP, IMAPS, LDAP, LDAPS, POP3, POP3S, RTMP, RTSP, SCP, SFTP, SMTP, SMTPS, TELNET and TFTP. *_cURL_* supports SSL certificates, HTTP POST, HTTP PUT, FTP uploading, HTTP form based upload, proxies, cookies, user+password authentication (Basic, Digest, NTLM, Negotiate, kerberos...), file transfer resume, proxy tunneling and a busload of other useful tricks. 

=== Quick & Professional Support

If you have any questions that aren't answered here or you need some special script to be developed, feel free to contact us: mailto:support@pdfburst.com[support@pdfburst.com]

=== We Need Feedback!

If you find a typographical error in this manual, or if you have thought of a way to make this manual better, we would love to hear from you!

If you have a suggestion for improving the documentation, try to be as specific as possible when describing it. If you have found an error, please include the section number and some surrounding text, so we can find it easily.

Email address: mailto:support@pdfburst.com[support@pdfburst.com]

Now let’s get started.