// ═══════════════════════════════════════════════════════════════════════════
// Northwind Sales Warehouse cube (OLAP star schema)
// ═══════════════════════════════════════════════════════════════════════════
//
// Cube source: vw_sales_detail (denormalized view in the bundled DuckDB warehouse)
// Connection: rbt-sample-northwind-duckdb-4f2
//
// Entire point: OLAP-style dimensional analysis of sales — pivot by time \u00d7
// geography \u00d7 product \u00d7 employee, with pre-computed gross/net revenue measures.
// Demonstrates the dimensional modeling pattern. Matches the existing Sales
// PivotTable sample (g-pivottable).
//
// Targets the OLAP star schema generated by NorthwindOlapDataGenerator:
//   - fact_sales (~8000 rows, one per transaction line)
//   - dim_customer (30 customers across 10 countries / 4 continents)
//   - dim_product  (16 products across 8 categories)
//   - dim_employee (3 sales reps)
//   - dim_time     (672 days, 2023-01 through 2024-12)
//   - vw_sales_detail (LEFT JOIN of fact + all 4 dims \u2014 the queryable surface)
//
// The view is fully denormalized \u2014 no joins needed in the cube DSL.
// ═══════════════════════════════════════════════════════════════════════════

cube {
  sql_table 'vw_sales_detail'
  title 'Northwind Sales Warehouse'
  description 'OLAP sales analysis with pre-computed measures over the DuckDB data warehouse'

  // ── Dimensions: Transaction-level (for per-transaction browsing) ──────
  // Pick SalesKey (and optionally DateKey) when you want one row per individual
  // sale transaction \u2014 the most granular grain. For pivot/aggregation analysis
  // (the warehouse's primary use case) use the time/customer/product/employee
  // dimensions instead.
  dimension {
    name 'SalesKey'
    title 'Sales Key'
    description 'Unique transaction identifier. Pick this dimension to establish per-transaction grain for browsing the raw fact table.'
    sql 'sales_key'
    type 'number'
    primary_key true
  }
  dimension {
    name 'DateKey'
    title 'Transaction Date'
    description 'Day-level date of the transaction. Useful in per-transaction browsing alongside SalesKey.'
    sql 'date_key'
    type 'time'
  }

  // ── Dimensions: Time ───────────────────────────────────────────────────
  dimension {
    name 'Year'
    title 'Year'
    description 'Calendar year (2023 or 2024)'
    sql 'year'
    type 'number'
  }
  dimension {
    name 'YearQuarter'
    title 'Year-Quarter'
    description 'Combined year and quarter (e.g. "2023-Q1")'
    sql 'year_quarter'
    type 'string'
  }
  dimension {
    name 'MonthName'
    title 'Month'
    description 'Month name (January, February, ...)'
    sql 'month_name'
    type 'string'
  }

  // ── Dimensions: Customer ───────────────────────────────────────────────
  dimension {
    name 'CustomerName'
    title 'Customer'
    description 'Customer company name'
    sql 'customer_name'
    type 'string'
  }
  dimension {
    name 'CustomerCountry'
    title 'Country'
    description 'Customer country'
    sql 'customer_country'
    type 'string'
  }
  dimension {
    name 'Continent'
    title 'Continent'
    description 'Customer continent (North America, Europe, etc.)'
    sql 'continent'
    type 'string'
  }

  // ── Dimensions: Product ────────────────────────────────────────────────
  dimension {
    name 'CategoryName'
    title 'Category'
    description 'Product category (Beverages, Dairy, Meat/Poultry, etc.)'
    sql 'category_name'
    type 'string'
  }
  dimension {
    name 'ProductName'
    title 'Product'
    description 'Product name'
    sql 'product_name'
    type 'string'
  }

  // ── Dimensions: Employee ───────────────────────────────────────────────
  dimension {
    name 'EmployeeName'
    title 'Sales Rep'
    description 'Employee who made the sale'
    sql 'employee_name'
    type 'string'
  }

  // ── Measures ────────────────────────────────────────────────────────────
  measure {
    name 'TransactionCount'
    title 'Transactions'
    description 'Number of distinct sales transactions'
    sql 'sales_key'
    type 'count_distinct'
  }
  measure {
    name 'TotalQuantity'
    title 'Units Sold'
    description 'Total units sold across all transactions'
    sql 'quantity'
    type 'sum'
  }
  measure {
    name 'GrossRevenue'
    title 'Gross Revenue'
    description 'Pre-discount revenue (quantity \u00d7 unit_price). Compare against NetRevenue to see discount impact.'
    sql 'gross_revenue'
    type 'sum'
    format 'currency'
  }
  measure {
    name 'NetRevenue'
    title 'Net Revenue (after discount)'
    description 'Post-discount revenue (the primary business measure)'
    sql 'net_revenue'
    type 'sum'
    format 'currency'
  }
  measure {
    name 'AvgUnitPrice'
    title 'Average Unit Price'
    description 'Average unit price across all transactions'
    sql 'unit_price'
    type 'avg'
    format 'currency'
  }
  measure {
    name 'AvgDiscountRate'
    title 'Avg Discount Rate'
    description 'Average discount rate applied'
    sql 'discount_rate'
    type 'avg'
  }
  measure {
    name 'UniqueCustomers'
    title 'Unique Customers'
    description 'Number of distinct customers'
    sql 'customer_name'
    type 'count_distinct'
  }
  measure {
    name 'UniqueProducts'
    title 'Unique Products'
    description 'Number of distinct products sold'
    sql 'product_name'
    type 'count_distinct'
  }

  // ── Segments ────────────────────────────────────────────────────────────
  segment {
    name 'with_discount'
    title 'Discounted Sales'
    description 'Transactions with a non-zero discount'
    sql '${CUBE}.discount_rate > 0'
  }
  segment {
    name 'north_america'
    title 'North America'
    description 'Sales to customers in North America'
    sql "\${CUBE}.continent = 'North America'"
  }
  segment {
    name 'europe'
    title 'Europe'
    description 'Sales to customers in Europe'
    sql "\${CUBE}.continent = 'Europe'"
  }

  // ── Hierarchies ─────────────────────────────────────────────────────────
  hierarchy {
    name 'time'
    title 'Time'
    levels 'Year', 'YearQuarter', 'MonthName'
  }
  hierarchy {
    name 'geography'
    title 'Customer Geography'
    levels 'Continent', 'CustomerCountry', 'CustomerName'
  }
  hierarchy {
    name 'product'
    title 'Product Taxonomy'
    levels 'CategoryName', 'ProductName'
  }
}
